baseURL = 'https://vedevilolivedev.github.io'
languageCode = 'en-us'
title = 'Vedevilolivedev Blog'
theme = 'terminal'
[params]
    themeColor = "blue"
    showMenuItems = 2
    enableGitInfo = true
    centerTheme = false
[languages]
  [languages.en]
    languageName = "English"
    title = "vedevilolivedev Blog"
    subtitle = "Random dev nerdery"
    owner = "vedevilolivedev"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Page not found..."
    missingBackButtonLabel = "Back to home page"

    [languages.en.params.logo]
      logoText = "vedevilolivedev Blog"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "showcase"
        name = "Showcase"
        url = "/showcase"
